openapi: 3.0.0
info:
  description: Services for managing persons and connections
  version: "1.0.0"
  title: UdaConnect API
paths:
  "/api/persons":
    get:
      summary: Retrieve persons
      operationId: get_persons_resource
      description: Retrieve persons
      responses:
        "200":
          description: Success
          content:
          application/json:
            schema:
              $ref: "#/components/schemas/Person"
        "404":
          description: Requested person ID was not found
    post:
      summary: Creates person
      operationId: post_persons_resource
      description: Creates person
      responses:
        "200":
          description: Success
        "400":
          description: Invalid input
        "409":
          description: This person already exists
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Person"
        description: Person to add
  "/api/persons/{person_id}":
    get:
      summary: Retrieve single person
      operationId: get_person_resource
      description: Success
      parameters:
        - in: path
          name: itemId
          schema:
            type: string
          required: true
          description: ID of the person to get
      responses:
        "200":
          description: Successfully retrieved a person
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InventoryItem"
        "404":
          description: Requested person ID was not found
components:
  schemas:
    Person:
      type: object
      required:
        - id
        - first_name
        - last_name
        - company_name
      properties:
        id:
          type: int
          example: 1
        name:
          type: string
          example: "Frank"
        brandName:
          type: string
          example: "Shader"
        weight:
          type: string
          example: "USDA"